annotations:
  category: developpment
  artifacthub.io/images: |
    - name: code-server
      image: docker.io/captnbp/code-server:4.19.0-r0
    - name: jupyterhub
      image: docker.io/bitnami/jupyterhub:4.0.2-debian-11-r55
    - name: oauth
      image: docker.io/captnbp/oauth:4.19.0-r0
    - name: nginx
      image: docker.io/captnbp/nginx:4.19.0-r0
    - name: configurable-http-proxy
      image: docker.io/bitnami/configurable-http-proxy:4.6.0-debian-11-r16
  artifacthub.io/license: MIT
apiVersion: v2
appVersion: 4.19.0-r0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Codehub brings the power of JupyterHub with Code-Server. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
engine: gotpl
home: https://jupyter.org/hub
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - devops
  - ide
  - vscode
maintainers:
  - name: captnbp
    url: https://lab.frogg.it/captnbp/codehub
name: codehub
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  - https://github.com/jupyterhub/jupyterhub
  - https://github.com/coder/code-server
version: 4.1.14
