annotations:
  category: developpment
  artifacthub.io/images: |
    - name: code-server
      image: docker.io/captnbp/code-server:4.105.1-r0
    - name: jupyterhub
      image: docker.io/bitnamilegacy/jupyterhub:5.3.0-debian-12-r16
    - name: oauth
      image: docker.io/captnbp/oauth:4.105.1-r0
    - name: nginx
      image: docker.io/captnbp/nginx:4.105.1-r0
    - name: configurable-http-proxy
      image: docker.io/bitnamilegacy/configurable-http-proxy:5.0.1-debian-12-r21
    - name: os-shell
      image: docker.io/bitnamilegacy/os-shell:12-debian-12-r51
  artifacthub.io/license: MIT
apiVersion: v2
appVersion: 4.105.1
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Codehub brings the power of JupyterHub with Code-Server. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
home: https://jupyter.org/hub
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - devops
  - ide
  - vscode
maintainers:
  - name: captnbp
    url: https://lab.frogg.it/doca/codehub-helm
name: codehub
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  - https://github.com/jupyterhub/jupyterhub
  - https://github.com/coder/code-server
version: 6.2.8
