annotations:
  category: developpment
  artifacthub.io/images: |
    - name: code-server
      image: docker.io/captnbp/code-server:4.100.2-r0
    - name: jupyterhub
      image: docker.io/bitnami/jupyterhub:5.3.0-debian-12-r8
    - name: oauth
      image: docker.io/captnbp/oauth:4.100.2-r0
    - name: nginx
      image: docker.io/captnbp/nginx:4.100.2-r0
    - name: configurable-http-proxy
      image: docker.io/bitnami/configurable-http-proxy:4.6.3-debian-12-r10
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r45
  artifacthub.io/license: MIT
apiVersion: v2
appVersion: 4.100.2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Codehub brings the power of JupyterHub with Code-Server. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
engine: gotpl
home: https://jupyter.org/hub
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - devops
  - ide
  - vscode
maintainers:
  - name: captnbp
    url: https://lab.frogg.it/captnbp/codehub
name: codehub
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  - https://github.com/jupyterhub/jupyterhub
  - https://github.com/coder/code-server
version: 6.1.0
