---
image: captnbp/gitlab-ci-image:latest

stages:
  - test
  - build
  - release

.template:helm:lint:
  stage: test
  script:
    - cd ${CHART_NAME}
    - helm dependency update
    - helm lint .
  tags:
    - server

.template:helm:publish:
  stage: release
  script:
    - cd ${CHART_NAME}
    - helm dependency update
    - helm package .
    - export CHART=$(ls ${CHART_NAME}-*.tgz)
    - helm registry login lab.frogg.it:5050 --username gitlab-ci-token --password ${CI_JOB_TOKEN} 
    - helm push ${CHART} oci://lab.frogg.it:5050/captnbp/
    - helm registry login registry-1.docker.io --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} 
    - helm push ${CHART} oci://registry-1.docker.io/captnbp/
  tags:
    - server

lint:
  extends:
    - .template:helm:lint
  variables:
    CHART_NAME: codehub

publish:
  extends:
    - .template:helm:publish
  variables:
    CHART_NAME: codehub
  rules:
    - if: $CI_COMMIT_TAG
