{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $offloadHTTPS := and $HTTPS (eq .Values.proxy.https.type "offload") -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- $manualHTTPSwithCertificate := and $HTTPS (eq .Values.proxy.https.type "cert-manager") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyterhub.fullname" . }}-proxy-api
  labels:
    {{- $_ := merge (dict "componentSuffix" "-api") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyterhub.fullname" . }}-proxy-public
  labels:
    {{- $_ := merge (dict "componentSuffix" "-public") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
    {{- if .Values.proxy.service.labels }}
    {{- .Values.proxy.service.labels | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
    {{- .Values.proxy.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    {{- if $HTTPS }}
    - name: https
      port: 443
      protocol: TCP
      {{- if or $manualHTTPS $manualHTTPSwithsecret $manualHTTPSwithCertificate }}
      targetPort: 8443
      {{- else if $offloadHTTPS }}
      targetPort: 8000
      {{- else }}
      targetPort: 443
      {{- end }}
      {{- if .Values.proxy.service.nodePorts.https }}
      nodePort: {{ .Values.proxy.service.nodePorts.https }}
      {{- end }}
    {{- end }}
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
      # allow proxy.service.nodePort for http
      {{- if .Values.proxy.service.nodePorts.http }}
      nodePort: {{ .Values.proxy.service.nodePorts.http }}
      {{- end }}
  type: {{ .Values.proxy.service.type }}
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- .Values.proxy.service.loadBalancerSourceRanges | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
