{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $offloadHTTPS := and $HTTPS (eq .Values.proxy.https.type "offload") -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- $manualHTTPSwithCertificate := and $HTTPS (eq .Values.proxy.https.type "cert-manager") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyterhub.fullname" . }}-proxy-api
  labels:
    {{- $_ := merge (dict "componentSuffix" "-api") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyterhub.fullname" . }}-proxy-public
  labels:
    {{- $_ := merge (dict "componentSuffix" "-public") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
    app.kubernetes.io/component: proxy
    {{- if .Values.proxy.service.labels }}
    {{- .Values.proxy.service.labels | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
    {{- .Values.proxy.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    {{- if $HTTPS }}
    - name: https
      port: 443
      # When HTTPS termination is handled outside our helm chart, pass traffic
      # coming in via this Service's port 443 to targeted pod's port meant for
      # HTTP traffic.
      {{- if $offloadHTTPS }}
      targetPort: http
      {{- else }}
      targetPort: https
      {{- end }}
      {{- with .Values.proxy.service.nodePorts.https }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
    - name: http
      port: 80
      targetPort: http
      {{- with .Values.proxy.service.nodePorts.http }}
      nodePort: {{ . }}
      {{- end }}
    {{- with .Values.proxy.service.extraPorts }}
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  type: {{ .Values.proxy.service.type }}
  {{- with .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if eq .Values.proxy.service.type "LoadBalancer" }}
  {{- with .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- end }}