{{- if .Values.hub.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "jupyterhub.fullname" . }}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  {{- if not (typeIs "<nil>" .Values.hub.pdb.maxUnavailable) }}
  maxUnavailable: {{ .Values.hub.pdb.maxUnavailable }}
  {{- end }}
  {{- if not (typeIs "<nil>" .Values.hub.pdb.minAvailable) }}
  minAvailable: {{ .Values.hub.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
{{- end }}
