apiVersion: v1
kind: Service
metadata:
  name: {{ template "jupyterhub.fullname" . }}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.hub.service.annotations }}
    {{- .Values.hub.service.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if .Values.hub.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      {{- if .Values.hub.service.ports.nodePort }}
      nodePort: {{ .Values.hub.service.ports.nodePort }}
      {{- end }}
