{{- if not .Values.hub.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codehub.hub.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: hub
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  apiToken: {{ include "codehub.hub.config.apiToken" . | b64enc | quote }}
  hub.config.JupyterHub.cookie_secret: {{ include "codehub.hub.config.JupyterHub.cookie_secret" . | b64enc | quote }}
  hub.config.CryptKeeper.keys: {{ include "codehub.hub.config.CryptKeeper.keys" . | b64enc | quote }}
{{- end }}
