{{- if .Values.scheduling.userScheduler.enabled -}}
{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jupyterhub.fullname" . }}-user-scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "jupyterhub.fullname" . }}-user-scheduler-base
  labels:
    {{- $_ := merge (dict "componentSuffix" "-base") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "jupyterhub.fullname" . }}-user-scheduler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "jupyterhub.fullname" . }}-user-scheduler-complementary
  labels:
    {{- $_ := merge (dict "componentSuffix" "-complementary") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
rules:
  # Support leader elections
  - apiGroups: [""]
    resourceNames: ["{{ template "jupyterhub.fullname" . }}-user-scheduler"]
    resources: ["configmaps"]
    verbs: ["get", "update"]
  # Workaround for missing permission in system:kube-scheduler as of k8s 1.10.4
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  # Workaround for missing permission with rancher local-path-provisioner
  - apiGroups: [""]
    resources: ["persistentvolume", "persistentvolumeclaims"]
    verbs: ["update"]
  {{- if .Values.psp.create }}
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - {{ template "jupyterhub.fullname" . }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "jupyterhub.fullname" . }}-user-scheduler-complementary
  labels:
    {{- $_ := merge (dict "componentSuffix" "-complementary") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "jupyterhub.fullname" . }}-user-scheduler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "jupyterhub.fullname" . }}-user-scheduler-complementary
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
